# -*- coding: -utf-8 -*-
import random
from django.db import migrations


PUNTAJE_MINIMO = 85
PUNTAJE_MAXIMO = 100


def insert_data(apps, schema_editor):
    paises = [
        'Rusia',
        'Arabia Saudita',
        'Egipto',
        'Uruguay',
        'Portugal',
        'España',
        'Marruecos',
        'Iran',
        'Francia',
        'Australia',
        'Perú',
        'Dinamarca',
        'Argentina',
        'Islandia',
        'Croacia',
        'Nigeria',
        'Brasil',
        'Suiza',
        'Costa Rica',
        'Serbia',
        'Alemania',
        'México',
        'Suecia',
        'República de Corea',
        'Bélgica',
        'Panamá',
        'Túnez',
        'Inglaterra',
        'Polonia',
        'Senegal',
        'Colombia',
        'Japón',
    ]
    Seleccion = apps.get_model('app', 'Seleccion')
    for pais in paises:
        Seleccion.objects.create(pais=pais)

    jugadores = [
        ('Jefferson FARFAN', 11),
        ('Jose CARVALLO', 11),
        ('Aldo CORZO', 11),
        ('Luis ADVINCULA', 11),
        ('Raul RUIDIAZ', 11),
        ('Renato TAPIA', 11),
        ('Pedro AQUINO', 11),
        ('Nilson LOYOLA', 11),
        ('Adrián ZELA', 11),
        ('Alberto RODRIGUEZ', 11),
        ('Pedro GALLESE', 11),
        ('Paolo HURTADO', 11),
        ('Yoshimar YOTUN', 11),
        ('Paolo GUERRERO', 11),
        ('Edison FLORES', 11),
        ('Miguel TRAUCO', 11),
        ('Christian RAMOS', 11),
        ('Carlos CACEDA', 11),
        ('Andre CARRILLO', 11),
        ('Christian CUEVA', 11),
        ('Miguel ARAUJO', 11),
        ('Andy POLO', 11),
        ('Anderson SANTAMARIA', 11),
        ('Lucas BIGLIA', 13),
        ('Sergio AGÜERO', 13),
        ('Lionel MESSI', 13),
        ('Federico FAZIO', 13),
        ('Angel DI MARIA', 13),
        ('Martin DEMICHELIS', 13),
        ('Ever BANEGA', 13),
        ('Gabriel MERCADO', 13),
        ('Nicolas GAITAN', 13),
        ('Mauro ICARDI', 13),
        ('Mariano ANDUJAR', 13),
        ('Erik LAMELA', 13),
        ('Pablo ZABALETA', 13),
        ('Nicolas OTAMEND', 13),
        ('Paulo DYBALA', 13),
        ('Ramiro FUNES MORI', 13),
        ('Emmanuel MAS', 13),
        ('Javier MASCHERANO', 13),
        ('Angel CORREA', 13),
        ('Javier PASTORE', 13),
        ('Sergio ROMERO', 13),
        ('Ezequiel GARAY', 13),
        ('Mateo MUSACCHIO', 13),
        ('DIEGO', 17),
        ('DANI ALVES', 17),
        ('DAVID LUIZ', 17),
        ('LUIZ GUSTAVO', 17),
        ('DOUGLAS COSTA', 17),
        ('NEYMAR', 17),
        ('FILIPE LUIS', 17),
        ('Xherdan SHAQIRI', 17),
        ('WILLIAN', 17),
        ('CASSIO', 17),
        ('THIAGO SILVA', 17),
        ('MARQUINHOS', 17),
        ('DANILO', 17),
        ('PAULINHO', 17),
        ('LUAN', 17),
        ('LUCAS LIMA', 17),
        ('MARCELO', 17),
        ('ALISSON', 17),
        ('OSCAR', 17),
        ('Roberto FIRMINO', 17),
        ('PHILIPPE COUTINHO', 17),
        ('xherdan SHAQIRI', 17),
        ('Robinson ZAPATA', 31),
        ('Abel AGUILAR', 31),
        ('Pablo ARMERO', 31),
        ('Fredy GUARIN', 31),
        ('David GONZALEZ', 31),
        ('Adrian RAMOS', 31),
        ('Macnelly TORRES', 31),
        ('Dayro MORENO', 31),
        ('Carlos VALDES', 31),
        ('David OSPINA', 31),
        ('Oscar MURILLO', 31),
        ('FALCAO', 31),
        ('James RODRIGUEZ', 31),
        ('Edgar PARDO', 31),
        ('Cristian BONILLA', 31),
        ('Gustavo CUELLAR', 31),
        ('Edwin CARDONA', 31),
        ('Jackson MARTINEZ', 31),
        ('Giovanni MORENO', 31),
        ('Stefan MEDINA', 31),
        ('Orlando BERRIO', 31),
        ('Luis MURIEL', 31),
        ('Duvan ZAPATA', 31),
        ('Sebastian PEREZ', 31),
        ('Carlos BACCA', 31),
        ('Martin SILVA', 4),
        ('Cristian RODRIGUEZ', 4),
        ('Fernando MUSLERA', 4),
        ('Cristhian STUANI', 4),
        ('Martin CACERES', 4),
        ('Edinson CAVANI', 4),
        ('Luis SUAREZ', 4),
        ('Jorge FUCILE', 4),
        ('Egidio AREVALO', 4),
        ('Esteban CONDE', 4),
        ('Alvaro GONZALEZ', 4),
        ('Mauricio VICTORINO', 4),
        ('Abel HERNANDEZ', 4),
        ('Nicolas LODEIRO', 4),
        ('Sebastian COATES', 4),
        ('Jonathan URRETAVISCAYA', 4),
        ('Camilo MAYADA', 4),
        ('Gaston RAMIREZ', 4),
        ('Martin CAMPANA', 4),
        ('Diego POLENTA', 4),
        ('Gaston SILVA', 4),
        ('Matias VECINO', 4),
        ('Giorgian DE ARRASCAETA', 4),
        ('Jose GIMENEZ', 4),
        ('Diego LAXALT', 4),
        ('Jose CALDERON', 26),
        ('Roman TORRES', 26),
        ('Luis HENRIQUEZ', 26),
        ('Blas PEREZ', 26),
        ('Jaime PENEDO', 26),
        ('Luis TEJADA', 26),
        ('Ricardo BUITRAGO', 26),
        ('Amilcar HENRIQUEZ', 26),
        ('Gabriel TORRES', 26),
        ('Luis OVALLE', 26),
        ('Rolando BLACKBURN', 26),
        ('Alberto QUINTERO', 26),
        ('Adolfo MACHADO', 26),
        ('Tony TAYLOR', 26),
        ('Roberto CHEN', 26),
        ('Darwin PINZON', 26),
        ('Abdiel ARROYO', 26),
        ('Harold CUMMINGS', 26),
        ('Eric DAVIS', 26),
        ('Manuel VARGAS', 26),
        ('Renan ADDLES', 26),
        ('Roderick MILLER', 26),
        ('Martin GOMEZ', 26),
        ('Jean Carlos CEDENO', 26),
        ('Alex RODRIGUEZ', 26),
        ('Pablo SALAZAR', 19),
        ('Randall AZOFEIFA', 19),
        ('Christian BOLANOS', 19),
        ('Keylor NAVAS', 19),
        ('Leonardo GONZALEZ', 19),
        ('Alvaro SABORIO', 19),
        ('Michael UMANA', 19),
        ('Junior DIAZ', 19),
        ('Bryan RUIZ', 19),
        ('Celso BORGES', 19),
        ('Dave MYRIE', 19),
        ('Giancarlo GONZALEZ', 19),
        ('Esteban ALVARADO', 19),
        ('Leonel MOREIRA', 19),
        ('David GUZMAN', 19),
        ('Bryan OVIEDO', 19),
        ('Yendrick RUIZ', 19),
        ('Oscar GRANADOS', 19),
        ('Kenner GUTIERREZ', 19),
        ('Diego MADRIGAL', 19),
        ('Joel CAMPBELL', 19),
        ('Yeltsin TEJEDA', 19),
        ('Danny CARVAJAL', 19),
        ('Oscar DUARTE', 19),
        ('Alfredo TALAVERA', 22),
        ('Rafael MARQUEZ', 22),
        ('Jose CORONA', 22),
        ('Moises MUNOZ', 22),
        ('Guillermo OCHOA', 22),
        ('Oribe PERALTA', 22),
        ('Jorge TORRES', 22),
        ('Javier HERNANDEZ', 22),
        ('Giovani DOS SANTOS', 22),
        ('Carlos VELA', 22),
        ('Hector MORENO', 22),
        ('Andres GUARDADO', 22),
        ('Rodolfo COTA', 22),
        ('Alejandro CASTRO', 22),
        ('Paul AGUILAR', 22),
        ('Luis MONTES', 22),
        ('Carlos PENA', 22),
        ('Diego REYES', 22),
        ('Hugo AYALA', 22),
        ('Jesus CORONA', 22),
        ('Jonathan DOS SANTOS', 22),
        ('Marco FABIAN', 22),
        ('Hector HERRERA', 22),
        ('Nestor ARAUJO', 22),
        ('Elias HERNANDEZ', 22),
        ('Alfred NDIAYE', 30),
        ('Henri SAIVET', 30),
        ('Younousse SANKHARE', 30),
        ('Lamine GASSAMA', 30),
        ('Moussa SOW', 30),
        ('Idrissa GUEYE', 30),
        ('Fallou DIAGNE', 30),
        ('Mbaye NIANG', 30),
        ('Kalidou KOULIBALY', 30),
        ('Papa Alioune NDIAYE', 30),
        ('Ludovic SANE', 30),
        ('Khadim NDIAYE', 30),
        ('Mohamed DIAME', 30),
        ('Kara MBODJI', 30),
        ('Zargo TOURE', 30),
        ('Cheikhou KOUYATE', 30),
        ('Baye NIASSE', 30),
        ('Moussa KONATE', 30),
        ('Famara DIEDHIOU', 30),
        ('Papa DIOP', 30),
        ('Youssouf SABALY', 30),
        ('Salif SANE', 30),
        ('Issa CISSOKHO', 30),
        ('Moussa WAGUE', 30),
        ('Obafemi MARTINS', 16),
        ('Daniel AKPEYI', 16),
        ('John Obi MIKEL', 16),
        ('Uwa ECHIEJILE', 16),
        ('Oladele AJIBOYE', 16),
        ('Rabiu IBRAHIM', 16),
        ('Brown IDEYE', 16),
        ('Ikechukwu EZENWA', 16),
        ('Victor MOSES', 16),
        ('Odion IGHALO', 16),
        ('Kenneth OMERUO', 16),
        ('Ogenyi ONAZI', 16),
        ('Orji KALU', 16),
        ('Jamiu ALIMI', 16),
        ('Ahmed MUSA', 16),
        ('Nosa IGIEBOR', 16),
        ('John OGU', 16),
        ('Kingsley MADU', 16),
        ('Uche AGBO', 16),
        ('Moses SIMON', 16),
        ('Onyinye NDIDI', 16),
        ('Musa MUHAMMED', 16),
        ('Kelechi IHEANACHO', 16),
        ('Dele ALAMPASU', 16),
        ('Ndubisi AGU', 16),
        ('Emmanuel DANIEL', 16),
        ('William EKONG', 16),
        ('Oghenekaro ETEBO', 16),
        ('Mark MILLIGAN', 10),
        ('Danny VUKOVIC', 10),
        ('Mile JEDINAK', 10),
        ('Tim CAHILL', 10),
        ('Robbie KRUSE', 10),
        ('James TROISI', 10),
        ('Nikita RUKAVYTSYA', 10),
        ('Matthew JURMAN', 10),
        ('Ryan McGOWAN', 10),
        ('Aaron MOOY', 10),
        ('Mathew LECKIE', 10),
        ('Milos DEGENEK', 10),
        ('Massimo LUONGO', 10),
        ('Maty RYAN', 10),
        ('Trent SAINSBURY', 10),
        ('Aziz BEHICH', 10),
        ('Jackson IRVINE', 10),
        ('Mitch LANGERAK', 10),
        ('Tommy ROGIC', 10),
        ('Bailey WRIGHT', 10),
        ('Tomi JURIC', 10),
        ('Joshua RISDON', 10),
        ('Alex GERSBACH', 10),
        ('James JEGGO', 10),
        ('ESSAM EL HADARY', 3),
        ('HOSSAM GHALY', 3),
        ('SHERIF EKRAMY', 3),
        ('Abdallah SAIED', 3),
        ('HOSSAM ASHOUR', 3),
        ('Mahmoud ABDELRAZEK', 3),
        ('ABDALLA SAID', 3),
        ('AHMED ELSHENAWY', 3),
        ('AHMED AL MUHAMADI', 3),
        ('WALID SOLIMAN', 3),
        ('AHMED FATHI', 3),
        ('AYMAN ASHRAF', 3),
        ('SAADELDIN SAAD', 3),
        ('MOHAMED EL NENY', 3),
        ('OMAR GABER', 3),
        ('MOHAMED SALAH', 3),
        ('AHMED TAWFIK', 3),
        ('HASSAN AHMED', 3),
        ('RABIA RAMY', 3),
        ('SALEH GOMAA', 3),
        ('IBRAHIM SALAH', 3),
        ('AHMED MEKKY', 3),
        ('MOHAMED ABDEL SHAFI', 3),
        ('MOHAMED NAGUIB', 3),
        ('TREZEGET', 3),
        ('AMR WARDA', 3),
        ('MAHMOUD KAHRABA', 3),
        ('AMR GAMAL', 3),
        ('Mohammed BOURKADI', 7),
        ('Mouhssine IAJOUR', 7),
        ('Karim EL AHMADI', 7),
        ('Aziz BENASKAR', 7),
        ('Mehdi CARCELA', 7),
        ('Noureddine AMRABAT', 7),
        ('Nabil DIRAR', 7),
        ('Mbark BOUSSOUFA', 7),
        ('MANUEL DA COSTA', 7),
        ('Younes BELHANDA', 7),
        ('Yassine BOUNOU', 7),
        ('Yassine EL KHARROUBI', 7),
        ('Ahmed TAGNAOUTI', 7),
        ('Amine HARIT', 7),
        ('Youssef AIT BENNASSER', 7),
        ('Monir EL KAJOUI', 7),
        ('Faycal FAJR', 7),
        ('Yacine BAMMOU', 7),
        ('Moestafa EL KABIR', 7),
        ('Hakim ZIYACH', 7),
        ('Marwane SAADANE', 7),
        ('Romain SAISS', 7),
        ('Oussama TANNANE', 7),
        ('Hamza MENDYL', 7),
        ('Hamdi HARBAOUI', 27),
        ('Yassine CHIKHAOUI', 27),
        ('Youssef MSAKNI', 27),
        ('Hamza LAHMAR', 27),
        ('Rami BEDOUI', 27),
        ('Ammar JEMAL', 27),
        ('Aymen ABDENNOUR', 27),
        ('Khelil CHAMMAM', 27),
        ('Farouk BEN MUSTAPHA', 27),
        ('Ahmed AKAICHI', 27),
        ('Moez BEN CHERIFIA', 27),
        ('Syam BEN YOUSSEF', 27),
        ('Taha KHENISSI', 27),
        ('Zied DERBALI', 27),
        ('Walid HICHRI', 27),
        ('Ali MAALOUL', 27),
        ('Mohamed Ali YAKOUBI', 27),
        ('Rami JERIDI', 27),
        ('Anis BEN HATIRA', 27),
        ('Chamseddine DHAOUADI', 27),
        ('Abdelkader OUESLATI', 27),
        ('Fakhreddine BEN YOUSSEF', 27),
        ('Alaya BRIGUI', 27),
        ('Fabien CAMUS', 27),
        ('Bilel MOHSNI', 27),
        ('Yassine MERIEH', 27),
        ('Hamza MATHLOUTHI', 27),
        ('Karim AOUADHI', 27),
        ('ASSAF AL QARNI', 2),
        ('YASSER AL MOSAILEM', 2),
        ('NASSER AL SHAMRANI', 2),
        ('WALEED ABDULLAH', 2),
        ('NAIF HAZAZI', 2),
        ('ABDULLAH ALHAFITH', 2),
        ('FAHAD AL MUWALLAD', 2),
        ('ABDULLAH OTAYF', 2),
        ('MOTAZ HAWSAWI', 2),
        ('MOHAMMED ALFATIL', 2),
        ('MUSTAFA AL BASSAS', 2),
        ('SALEM AL DAWSARI', 2),
        ('MANSOUR ALHARBI', 2),
        ('MUKHTAR FALLATAH', 2),
        ('SALMAN AL FARAJ', 2),
        ('SAEED AL MOWALAD', 2),
        ('YASSIN ALNAKHLI', 2),
        ('SALMAN ALMUWASHAR', 2),
        ('MOHAMMED ALOWAIS', 2),
        ('ABDULAZIZ ALJEBREEN', 2),
        ('ABDULLAH ALAWISHIR', 2),
        ('MOHAMMED ALBURAYK', 2),
        ('ABDULMAJEED ALRUWAILI', 2),
        ('ABDULRAHMAN OBAID', 2),
        ('Jalal HOSSEINI', 8),
        ('Mohammad AKHBARI', 8),
        ('Kaveh REZAEI', 8),
        ('Omid ALISHAH', 8),
        ('Hossein MAHINI', 8),
        ('Karim ANSARIFARD', 8),
        ('Kamaleddin KAMYABINIA', 8),
        ('Alireza JAHAN BAKHSH', 8),
        ('Soroush RAFIEI', 8),
        ('Ali KARIMI', 8),
        ('Meysam MAJIDI', 8),
        ('Mohammad MAZAHERI', 8),
        ('Dariush SHOJAEIAN', 8),
        ('Mohammad ANSARI', 8),
        ('Sasan ANSARI', 8),
        ('Hamed LAK', 8),
        ('Saeed AGHAEI', 8),
        ('Alireza SALIMI', 8),
        ('Roozbeh CHESHMI', 8),
        ('Omid NORAFKAN', 8),
        ('Ashkan DEJAGAH', 8),
        ('Masoud SHOJAEI', 8),
        ('Andranik TIMOTIAN', 8),
        ('Pejman MONTAZERI', 8),
        ('LEE Donggook', 24),
        ('CHOI Chulsoon', 24),
        ('KWOUN Suntae', 24),
        ('LEE Keunho', 24),
        ('KI Sungyueng', 24),
        ('PARK Jooho', 24),
        ('KOH Myongjin', 24),
        ('KIM Minwoo', 24),
        ('OH Jaesuk', 24),
        ('KIM Bokyung', 24),
        ('Kim YOUNG-GWON', 24),
        ('KIM Min Hyeok', 24),
        ('HWANG Uijo', 24),
        ('Go YO-HAN', 24),
        ('KIM Shinwook', 24),
        ('YUN Young Sun', 24),
        ('HONG Chul', 24),
        ('JI Dongwon', 24),
        ('KIM Keehee', 24),
        ('LEE Yong', 24),
        ('KWON Changhoon', 24),
        ('KIM Dongjun', 24),
        ('LEE Changmin', 24),
        ('HEO Yongjoon', 24),
        ('LEE Myungjoo', 24),
        ('KO Kwangmin', 24),
        ('HWANG Heechan', 24),
        ('Kim MINJAE', 24),
        ('Yasuyuki KONNO', 32),
        ('Akihiro HAYASHI', 32),
        ('Yosuke KASHIWAGI', 32),
        ('Mike HAVENAAR', 32),
        ('Takashi INUI', 32),
        ('Mu KANAZAKI', 32),
        ('Manabu SAITO', 32),
        ('Shinzo KOROKI', 32),
        ('Shu KURATA', 32),
        ('Yuki KOBAYASHI', 32),
        ('Kenyu SUGIMOTO', 32),
        ('Naomichi UEDA', 32),
        ('Takumi MINAMINO', 32),
        ('Kosuke NAKAMURA', 32),
        ('Hiroshi KIYOTAKE', 32),
        ('Hiroki FUJIHARU', 32),
        ('Yuya KUBO', 32),
        ('Tsukasa SHIOTANI', 32),
        ('Yu KOBAYASHI', 32),
        ('Gen SHOJI', 32),
        ('Tomoya UGAJIN', 32),
        ('Yuichi MARUYAMA', 32),
        ('Yosuke IDEGUCHI', 32),
        ('Koki YONEKURA', 32),
        ('Olafur SKULASON', 14),
        ('Kjartan FINNBOGASON', 14),
        ('Kari ARNASON', 14),
        ('Ragnar SIGURDSSON', 14),
        ('Birkir SAEVARSSON', 14),
        ('Emil HALLFREDSSON', 14),
        ('Elmar BJARNASON', 14),
        ('Johann GUDMUNDSSON', 14),
        ('Holmar EYJOLFSSON', 14),
        ('Ari SKULASON', 14),
        ('Birkir BJARNASON', 14),
        ('Gylfi SIGURDSSON', 14),
        ('Rurik GISLASON', 14),
        ('Aron GUNNARSSON', 14),
        ('Arnor SMARASON', 14),
        ('Hannes HALLDORSSON', 14),
        ('Bjorn SIGURDARSON', 14),
        ('Alfred FINNBOGASON', 14),
        ('Runar SIGURJONSSON', 14),
        ('Ogmundur KRISTINSSON', 14),
        ('Haukur HAUKSSON', 14),
        ('Sverrir INGASON', 14),
        ('Ingvar JONSSON', 14),
        ('Jon BODVARSSON', 14),
        ('RICARDO QUARESMA', 5),
        ('JOAO MOUTINHO', 5),
        ('CRISTIANO RONALDO', 5),
        ('BRUNO ALVES', 5),
        ('BETO', 5),
        ('ELISEU', 5),
        ('NANI', 5),
        ('ANTUNES', 5),
        ('RUI PATRICIO', 5),
        ('FABIO COENTRAO', 5),
        ('PEPE', 5),
        ('EDUARDO', 5),
        ('ADRIEN SILVA', 5),
        ('CEDRIC', 5),
        ('NELSON OLIVEIRA', 5),
        ('DANILO', 5),
        ('PIZZI', 5),
        ('LUIS NETO', 5),
        ('EDER', 5),
        ('ANDRE GOMES', 5),
        ('Bruma', 5),
        ('JOAO CANCELO', 5),
        ('JOSE SA', 5),
        ('BRUNO VARELA', 5),
        ('Pepe REINA', 6),
        ('Andres INIESTA', 6),
        ('David SILVA', 6),
        ('Sergio RAMOS', 6),
        ('Gerard PIQUE', 6),
        ('David VILLA', 6),
        ('Juan MATA', 6),
        ('David DE GEA', 6),
        ('NACHO', 6),
        ('Asier ILLARRAMENDI', 6),
        ('Javi MARTINEZ', 6),
        ('Cesar AZPILICUETA', 6),
        ('Jose Maria CALLEJON', 6),
        ('Sergio ASENJO', 6),
        ('Sergio BUSQUETS', 6),
        ('Jordi ALBA', 6),
        ('ISCO', 6),
        ('KOKE', 6),
        ('Sergi ROBERTO', 6),
        ('PACO ALCACER', 6),
        ('Alvaro MORATA', 6),
        ('PEDRO', 6),
        ('Marc BARTRA', 6),
        ('RODRIGO', 6),
        ('Inigo MARTINEZ', 6),
        ('Diego COSTA', 6),
        ('Dusko TOSIC', 20),
        ('Vladimir STOJKOVIC', 20),
        ('Branislav IVANOVIC', 20),
        ('Aleksandar KOLAROV', 20),
        ('Slobodan RAJKOVIC', 20),
        ('Antonio RUKAVINA', 20),
        ('Zoran TOSIC', 20),
        ('Aleksandar PRIJOVIC', 20),
        ('Ljubomir FEJSA', 20),
        ('Ivan OBRADOVIC', 20),
        ('Vladimir STOJKOVIC', 20),
        ('Dusan TADIC', 20),
        ('Nemanja MATIC', 20),
        ('Nemanja PEJCINOVIC', 20),
        ('Adem LJAJIC', 20),
        ('Jagos VUKOVIC', 20),
        ('Lazar MARKOVIC', 20),
        ('Predrag RAJKOVIC', 20),
        ('Uros DJURDJEVIC', 20),
        ('Nikola MAKSIMOVIC', 20),
        ('Matija NASTASIC', 20),
        ('Aleksandar IGNJOVSKI', 20),
        ('Filip MLADENOVIC', 20),
        ('Luka MILIVOJEVIC', 20),
        ('Aleksandar MITROVIC', 20),
        ('Nemanja MAKSIMOVIC', 20),
        ('Mijat GACINOVIC', 20),
        ('Luka MODRIC', 15),
        ('Ivan RAKITIC', 15),
        ('Vedran CORLUKA', 15),
        ('Nikola KALINIC', 15),
        ('Danijel SUBASIC', 15),
        ('Domagoj VIDA', 15),
        ('Dejan LOVREN', 15),
        ('Franko ANDRIJASEVIC', 15),
        ('Andrej KRAMARIC', 15),
        ('Sime VRSALJKO', 15),
        ('Marko LESKOVIC', 15),
        ('Mateo KOVACIC', 15),
        ('Ivan STRINIC', 15),
        ('Milan BADELJ', 15),
        ('Ivan PERISIC', 15),
        ('Dominik LIVAKOVIC', 15),
        ('Antonio MILIC', 15),
        ('Matej MITROVIC', 15),
        ('Marko PJACA', 15),
        ('Ante REBIC', 15),
        ('Duje CALETA-CAR', 15),
        ('Tin JEDVAJ', 15),
        ('Josip PIVARIC', 15),
        ('Ivan VARGIC', 15),
        ('Stephan LICHTSTEINER', 18),
        ('Valon BEHRAMI', 18),
        ('Johan DJOUROU', 18),
        ('Blerim DZEMAILI', 18),
        ('Gelson FERNANDES', 18),
        ('Eren DERDIYOK', 18),
        ('Valentin STOCKER', 18),
        ('Haris SEFEROVIC', 18),
        ('Granit XHAKA', 18),
        ('Ricardo RODRIGUEZ', 18),
        ('Yann SOMMER', 18),
        ('Fabian FREI', 18),
        ('Mario GAVRANOVIC', 18),
        ('Xherdan SHAQIRI', 18),
        ('Josip DRMIC', 18),
        ('Timm KLOSE', 18),
        ('Michael LANG', 18),
        ('Admir MEHMEDI', 18),
        ('Fabian SCHAER', 18),
        ('Silvan WIDMER', 18),
        ('Steven ZUBER', 18),
        ('Roman BUERKI', 18),
        ('Marwin HITZ', 18),
        ('Breel EMBOLO', 18),
        ('Patrice EVRA', 9),
        ('Steve MANDANDA', 9),
        ('Bacary SAGNA', 9),
        ('Sebastien CORCHIA', 9),
        ('Hugo LLORIS', 9),
        ('Adil RAMI', 9),
        ('Andre Pierre GIGNAC', 9),
        ('Moussa SISSOKO', 9),
        ('Eliaquim MANGALA', 9),
        ('Benjamin MENDY', 9),
        ('Kurt ZOUMA', 9),
        ('Aymeric LAPORTE', 9),
        ('Tiemoue BAKAYOKO', 9),
        ('Antoine GRIEZMANN', 9),
        ('Laurent KOSCIELNY', 9),
        ('Blaise MATUIDI', 9),
        ('Olivier GIROUD', 9),
        ('Christophe JALLET', 9),
        ('Raphael VARANE', 9),
        ('Dimitri PAYET', 9),
        ('Kevin GAMEIRO', 9),
        ('Paul POGBA', 9),
        ('Samuel UMTITI', 9),
        ('Lucas DIGNE', 9),
        ('Timmy SIMONS', 25),
        ('Vincent KOMPANY', 25),
        ('Nicolas LOMBAERTS', 25),
        ('Sebastien POCOGNOLI', 25),
        ('Thomas VERMAELEN', 25),
        ('Eden HAZARD', 25),
        ('Christian BENTEKE', 25),
        ('Steven DEFOUR', 25),
        ('Moussa DEMBELE', 25),
        ('Toby ALDERWEIRELD', 25),
        ('Marouane FELLAINI', 25),
        ('Kevin MIRALLAS', 25),
        ('Simon MIGNOLET', 25),
        ('Thibaut COURTOIS', 25),
        ('Nacer CHADLI', 25),
        ('Romelu LUKAKU', 25),
        ('Dries MERTENS', 25),
        ('Dedryck BOYATA', 25),
        ('Kevin DE BRUYNE', 25),
        ('Radja NAINGGOLAN', 25),
        ('Koen CASTEELS', 25),
        ('Thorgan HAZARD', 25),
        ('Michy BATSHUAYI', 25),
        ('Divock ORIGI', 25),
        ('Sami KHEDIRA', 21),
        ('Mario GOMEZ', 21),
        ('Manuel NEUER', 21),
        ('Kevin TRAPP', 21),
        ('Toni KROOS', 21),
        ('Jerome BOATENG', 21),
        ('Mesut OEZIL', 21),
        ('Andre SCHUERRLE', 21),
        ('Marc-Andre TER STEGEN', 21),
        ('Shkodran MUSTAFI', 21),
        ('Marvin PLATTENHARDT', 21),
        ('Mario GOETZE', 21),
        ('Benedikt HOEWEDES', 21),
        ('Mats HUMMELS', 21),
        ('Thomas MUELLER', 21),
        ('Emre CAN', 21),
        ('Ilkay GUNDOGAN', 21),
        ('Julian DRAXLER', 21),
        ('Matthias GINTER', 21),
        ('Leon GORETZKA', 21),
        ('Maximilian MEYER', 21),
        ('Antonio RUEDIGER', 21),
        ('Julian BRANDT', 21),
        ('Joshua KIMMICH', 21),
        ('Jermain DEFOE', 28),
        ('Wayne ROONEY', 28),
        ('Theo WALCOTT', 28),
        ('Danny WELBECK', 28),
        ('Danny ROSE', 28),
        ('Joe HART', 28),
        ('Phil JAGIELKA', 28),
        ('Gary CAHILL', 28),
        ('Danny DRINKWATER', 28),
        ('Kieran TRIPPIER', 28),
        ('Ryan BERTRAND', 28),
        ('Kieran GIBBS', 28),
        ('Daniel STURRIDGE', 28),
        ('Jack WILSHERE', 28),
        ('Jordan PICKFORD', 28),
        ('James WARD-PROWSE', 28),
        ('Nathaniel CHALOBAH', 28),
        ('Raheem STERLING', 28),
        ('Nathan REDMOND', 28),
        ('Nathaniel CLYNE', 28),
        ('Luke SHAW', 28),
        ('Michael KEANE', 28),
        ('Jordan HENDERSON', 28),
        ('Alex OXLADE CHAMBERLAIN', 28),
        ('Artur BORUC', 29),
        ('Lukasz FABIANSKI', 29),
        ('Jakub BLASZCZYKOWSKI', 29),
        ('Slawomir PESZKO', 29),
        ('Lukasz PISZCZEK', 29),
        ('Kamil GLIK', 29),
        ('Kamil GROSICKI', 29),
        ('Grzegorz KRYCHOWIAK', 29),
        ('Wojciech SZCZESNY', 29),
        ('Artur JEDRZEJCZYK', 29),
        ('Michal PAZDAN', 29),
        ('Tomasz JODLOWIEC', 29),
        ('Maciej RYBUS', 29),
        ('Robert LEWANDOWSKI', 29),
        ('Marcin KAMINSKI', 29),
        ('Rafal WOLSKI', 29),
        ('Maciej SADLOK', 29),
        ('Pawel WSZOLEK', 29),
        ('Lukasz SKORUPSKI', 29),
        ('Arkadiusz MILIK', 29),
        ('Lukasz TEODORCZYK', 29),
        ('Bartosz SALAMON', 29),
        ('Bartosz BERESZYNSKI', 29),
        ('Piotr ZIELINSKI', 29),
        ('Jesper HANSEN', 12),
        ('Nicklas BENDTNER', 12),
        ('Kasper SCHMEICHEL', 12),
        ('William KVIST', 12),
        ('Simon KJAER', 12),
        ('Lasse SCHONE', 12),
        ('Jonas LOSSL', 12),
        ('Lasse NIELSEN', 12),
        ('Andreas BJELLAND', 12),
        ('Mike JENSEN', 12),
        ('Henrik DALSGAARD', 12),
        ('Daniel WASS', 12),
        ('Mathias JORGENSEN', 12),
        ('Christian ERIKSEN', 12),
        ('Riza DURMISI', 12),
        ('Pierre-Emile HOJBJERG', 12),
        ('Viktor FISCHER', 12),
        ('Yussuf POULSEN', 12),
        ('Jannik VESTERGAARD', 12),
        ('Nicolai JORGENSEN', 12),
        ('Andreas CORNELIUS', 12),
        ('Jonas KNUDSEN', 12),
        ('Peter ANKERSEN', 12),
        ('Andreas GRANQVIST', 23),
        ('Sebastian LARSSON', 23),
        ('Oscar WENDT', 23),
        ('Marcus BERG', 23),
        ('Mikael LUSTIG', 23),
        ('Ola TOIVONEN', 23),
        ('Martin OLSSON', 23),
        ('Albin EKDAL', 23),
        ('Kristoffer NORDFELDT', 23),
        ('Jimmy DURMAZ', 23),
        ('Linus WAHLQVIST', 23),
        ('Oscar HILJEMARK', 23),
        ('Pontus JANSSON', 23),
        ('Ludwig AUGUSTINSSON', 23),
        ('Alexander FRANSSON', 23),
        ('Filip HELANDER', 23),
        ('Isaac THELIN', 23),
        ('Andreas LINDE', 23),
        ('Victor LINDELOF', 23),
        ('Ken SEMA', 23),
        ('Christoffer NYMAN', 23),
        ('Robin OLSEN', 23),
        ('Oscar LEWICKI', 23),
        ('Yuri Lodyguin', 1),
        ('Guilherme Marinato', 1),
        ('Román Shishkin', 1),
        ('Ígor Smólnikov', 1),
        ('Serguéi Ignashévich', 1),
        ('Iliá Kutépov', 1),
        ('Alekséi Berezutski', 1),
        ('Vasili Berezutski', 1),
        ('Gueorgui Schénnikov', 1),
        ('Artur Yusúpov', 1),
        ('Denís Glushakov', 1),
        ('Pável Mamáyev', 1),
        ('Aleksandr Golovin', 1),
        ('Román Shirókov', 1),
        ('Oleg Shátov', 1),
        ('Oleg Ivanov', 1),
        ('Aleksandr Samédov', 1),
        ('Dmitri Torbinski', 1),
        ('Dmitri Kombárov', 1),
        ('Aleksandr Kokorin', 1),
        ('Fiódor Smólov', 1),
        ('Artiom Dziuba', 1),
    ]

    Jugador = apps.get_model('app', 'Jugador')
    for nombre, pais_id in jugadores:
        Jugador.objects.create(
            nombre=nombre,
            pais_id=pais_id,
            puntaje=random.randint(PUNTAJE_MINIMO, PUNTAJE_MAXIMO)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
